#ifndef T_INPUT_H
#define T_INPUT_H
#include <stdbool.h>

typedef enum {
	KEYCODE_UNKOWN = -1, KEYCODE_SPACE = 32, KEYCODE_APOSTROPHE = 39,
	KEYCODE_COMMA = 44, KEYCODE_MINUS, KEYCODE_PERIOD, KEYCODE_SLASH,
	KEYCODE_0, KEYCODE_1, KEYCODE_2, KEYCODE_3, KEYCODE_4, KEYCODE_5,
	KEYCODE_6, KEYCODE_7, KEYCODE_8, KEYCODE_9, KEYCODE_SEMICOLON = 59,
	KEYCODE_EQUAL = 61, KEYCODE_A = 65, KEYCODE_B, KEYCODE_C, KEYCODE_D,
	KEYCODE_E, KEYCODE_F, KEYCODE_G, KEYCODE_H, KEYCODE_I, KEYCODE_J,
	KEYCODE_K, KEYCODE_L, KEYCODE_M, KEYCODE_N, KEYCODE_O, KEYCODE_P, KEYCODE_Q,
	KEYCODE_R, KEYCODE_S, KEYCODE_T, KEYCODE_U, KEYCODE_V, KEYCODE_W, KEYCODE_X,
	KEYCODE_Y, KEYCODE_Z, KEYCODE_LEFT_BRACKET = 91, KEYCODE_BACKLASH = 92,
	KEYCODE_RIGHT_BRACKET = 93, KEYCODE_GRAVE_ACCENT = 96, KEYCODE_WORLD_1 = 161,
	KEYCODE_WORLD_2 = 162, KEYCODE_ESCAPE = 256, KEYCODE_ENTER, KEYCODE_TAB,
	KEYCODE_BACKSPACE, KEYCODE_INSERT, KEYCODE_DELETE, KEYCODE_RIGHT, KEYCODE_LEFT,
	KEYCODE_DOWN, KEYCODE_UP, KEYCODE_PAGE_UP, KEYCODE_PAGE_DOWN, KEYCODE_HOME, KEYCODE_END,
	KEYCODE_CAPS_LOCK = 280, KEYCODE_SCROLL_LOCK, KEYCODE_NUM_LOCK, KEYCODE_PRINT_SCREEN, KEYCODE_PAUSE,
	KEYCODE_F1 = 290, KEYCODE_F2, KEYCODE_F3, KEYCODE_F4, KEYCODE_F5, KEYCODE_F6, KEYCODE_F7, KEYCODE_F8,
	KEYCODE_F9, KEYCODE_F10, KEYCODE_F11, KEYCODE_F12, KEYCODE_LEFT_SHIFT = 340, KEYCODE_LEFT_CONTROL,
	KEYCODE_LEFT_ALT, KEYCODE_LEFT_SUPER, KEYCODE_RIGHT_SHIFT, KEYCODE_RIGHT_CONTROL, KEYCODE_RIGHT_ALT,
	KEYCODE_RIGHT_SUPER, KEYCODE_MENU, KEYCODE_COUNT
} KEYCODE;

bool input_get_key(enum KEYCODE code);
bool input_key_clicked(enum KEYCODE code);
bool input_mouse_clicked(int id);

float input_mouse_x();
float input_mouse_y();
float input_mouse_prev_x();
float input_mouse_prev_y();
void  input_cursor_lock(bool value);
void  input_sync();
void  input_reset();

#endif // !T_INPUT_H
